from selenium.webdriver.common.by import By

#page settings for fixtures
page_home_set = ((By.CSS_SELECTOR, 'div[class="dashboard-card calendar-card"] h3'), 'Календарь событий')
page_main_menu_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 start-page__header"]'), 'Работа с объектами учета')
page_search_by_sections_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 type-information-page__header"]'), 'Выберите тип имущества для поиска по разделам')
page_search_by_land_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 1.1')
page_search_by_building_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 1.2')
page_search_by_room_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 1.3')
page_search_by_ship_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 1.4')
page_search_by_stock_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 2.1')
page_search_by_investment_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 2.2')
page_search_by_movable_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 2.3')
page_search_by_transport_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 2.4')
page_search_by_other_move_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 2.5')
page_search_by_share_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 2.6')
page_search_by_holder_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-filter-block__header"]'), 'Поиск разделов 3.1')
page_search_by_change_record_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-change-record-page__header"]'), 'Поиск по записям')
page_search_by_request_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-request-filter-block__header"]'), 'Поиск по запросам')
page_search_by_rfi_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 search-federal-property-register-page-filter-block__header"] span'), 'Поиск в Реестре федерального имущества')
page_excerpt_request_search_set = ((By.CSS_SELECTOR, 'h1[class="header header_h1 rfi-request-filter-block__header"] span'), 'Запросы на предоставление выписок РФИ')
page_excerpt_request_create_set = ((By.CSS_SELECTOR, 'h1 div'), 'Формирование запроса на предоставление выписок из РФИ')
page_excerpt_request_set = ((By.CSS_SELECTOR, 'h1 div'), 'Запрос на предоставление выписок из РФИ')